### DISCUSSION TITLE
Is it possible to use this for private repos and projects?

### DISCUSSION THREAD

**Discussion by iwishiwasaneagle** [leonsteinhaeuser/project-beta-automations#37] [Q&A] [answered]
What the title says. I'm struggling to get it to work with my private repo and projects

**Comment by leonsteinhaeuser** [comment, marked as answer]
@iwishiwasaneagle to answer the title question: yes, it is definitely possible. I use this myself in several repositories.

The configuration for private repositories is the same as for public repositories.

Example: https://github.com/leonsteinhaeuser/project-beta-automations/blob/main/.github/workflows/project_automations.yml

I'm not sure if you read the "Note" at the beginning of the README:

> Note: GITHUB_TOKEN does not have the necessary scopes to access projects (beta).
> You must create a token with ***org:write*** scope and save it as a secret in your repository or organization.
> For more information, see [Creating a personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token).

If you have done this and it still does not work, try to add `DEBUG_COMMANDS: true` and `DEBUG_LOG: true` (as env) and send me the output.

```yaml
      ...
      - name: Move issue to ...
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        env:
          DEBUG_COMMANDS: true
          DEBUG_LOG: true
```
