### DISCUSSION TITLE
Is there a way to have PR from external contributor to work?

### DISCUSSION THREAD

**Discussion by ericbsd** [leonsteinhaeuser/project-beta-automations#63] [Q&A] [answered]
When I get PR from forks, I get this error.

```
Run leonsteinhaeuser/project-beta-automations@v2.1.0
  with:
    organization: ghostbsd
    project_id: 4
    resource_node_id: PR_kwDOAQFpzM5O8E48
    status_value: In Review
    operation_mode: status
    move_related_issues: false
  env:
    in_review: In Review
Run /home/runner/work/_actions/leonsteinhaeuser/project-beta-automations/v2.1.0/deps.sh
  /home/runner/work/_actions/leonsteinhaeuser/project-beta-automations/v2.1.0/deps.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    in_review: In Review
gh cli is installed.
Run echo "No GH Auth method configured, provide PAT or App ID/Key"; exit 1
  echo "No GH Auth method configured, provide PAT or App ID/Key"; exit 1
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    in_review: In Review
No GH Auth method configured, provide PAT or App ID/Key
Error: Process completed with exit code 1.
```

**Comment by ericbsd** [comment]
Here is the yaml code:
```
name: Project automations

on:
  pull_request:
    types:
      - opened

# map fields with customized labels
env:
  in_review: In Review

jobs:
  pr_opened:
    name: pr_opened
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'opened')
    steps:
      - name: Move PR to ${{ env.in_review }}
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          # user: ghostbsd
          organization: ghostbsd
          project_id: 4
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.in_review }}
```

**Reply by leonsteinhaeuser** [reply, marked as answer]
@ericbsd have you tried `pull_request_target` instead of `pull_request`?

**Reply by ericbsd** [reply]
> @ericbsd have you tried `pull_request_target` instead of `pull_request`?

I will try that.

**Reply by ericbsd** [reply]
@leonsteinhaeuser pull_request_target has skipped the workflow.

**Reply by leonsteinhaeuser** [reply]
Your configuration looks something like this, right?

```yaml
on:
  pull_request_target:
    types:
      - opened
jobs:
  pr_opened:
    name: pr_opened
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Move PR to ${{ env.in_progress }}
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ env.gh_pat }}
          organization: ${{ env.organization }}
          project_id: ${{ env.project }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.in_progress }}
```

**Reply by ericbsd** [reply]
> Your configuration looks something like this, right?
> 
> ```yaml
> on:
>   pull_request_target:
>     types:
>       - opened
> jobs:
>   pr_opened:
>     name: pr_opened
>     runs-on: ubuntu-latest
>     if: github.event_name == 'pull_request' && github.event.action == 'opened'
>     steps:
>       - name: Move PR to ${{ env.in_progress }}
>         uses: leonsteinhaeuser/project-beta-automations@v2.1.0
>         with:
>           gh_token: ${{ env.gh_pat }}
>           organization: ${{ env.organization }}
>           project_id: ${{ env.project }}
>           resource_node_id: ${{ github.event.pull_request.node_id }}
>           status_value: ${{ env.in_progress }}
> ```

Yes.

I just did a change. I did remove `github.event_name == 'pull_request'` in the if condition and that fixed the issue.

Thanks for the tip. It is now working.

**Reply by leonsteinhaeuser** [reply]
Great. If you like, you could open a pull request and add your example to the README.

**Reply by ericbsd** [reply]
I will take the time to do that.

**Comment by ericbsd** [comment]
The code below is working.
```yaml
name: Project automations

on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'master'

# map fields with customized labels
env:
  in_review: In Review

jobs:
  pr_opened:
    name: pr_opened
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.event.action == 'opened'
    steps:
      - name: Move PR to ${{ env.in_review }}
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          # user: ghostbsd
          organization: ghostbsd
          project_id: 4
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.in_review }}
```
