### DISCUSSION TITLE
Is that possible to set started_at field when event become In Progress?

### DISCUSSION THREAD

**Discussion by dmirell** [leonsteinhaeuser/project-beta-automations#83] [General]
Is that possible to set started_at field when I move my issue to In progress state?

**Comment by leonsteinhaeuser** [comment]
Hello @dmirell,

If I understood you correctly, you would like to do the following:

--> Issue set to in Progress --> Set started_at to `@current` (interation for example).

As this action supports changes for each field, you should be able to do this. You can find the property definition for the fields here: https://github.com/leonsteinhaeuser/project-beta-automations#json-definition

The following action should apply to your use case (not tested).

```yaml
on:
  issues:

jobs:
  issue_project_custom_field_update:
    name: issue_opened_or_reopened
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          user: sample-user
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "In Progress"

      - name: 'Set started at'
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        env:
          DEBUG_LOG: "true"
        with:
          gh_token: ${{ env.gh_project_token }}
          organization: ${{ env.gh_organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          operation_mode: custom_field
          custom_field_values: `[{\"name\": \"started_at\",\"type\": \"iteration\",\"value\": \"@current\"}]`
```
