### ISSUE TITLE
[BUG] entrypoint.sh: No such file or directory

### ISSUE THREAD

**Issue by leonsteinhaeuser** [leonsteinhaeuser/project-beta-automations#1]
**Describe the bug**
entrypoint.sh could not be found during ci run.

```
/home/runner/work/_temp/***bad6ff2-aced-44***2-bcb7-c13***b2cd6860.sh: line 1: ./entrypoint.sh: No such file or directory
Error: Process completed with exit code 127.
```

**To Reproduce**
1. Define the workflow steps with values like
```yaml
    steps:
      - name: 'Move issue to Todo'
        uses: leonsteinhaeuser/project-beta-automations@v0.0.1
        with:
          github_token: $GITHUB_TOKEN
          organization: $ORGANIZATION
          project_id: $PROJECT_NUMBER
          resource_node_id: $ISSUE_ID
          status_value: "Todo"
```

**Expected behavior**
I expected to see the issue on my project board.

**Workflow (please complete the following information):**
 - OS: [e.g. ubuntu-latest]
 - App version [e.g. v0.0.1]
