### ISSUE TITLE
[Feature Request] Ability to set custom fields (other than status) value

### ISSUE THREAD

**Issue by nddery** [leonsteinhaeuser/project-beta-automations#22]
**Is your feature request related to a problem? Please describe.**
Some of our board view are driven by the value of a custom field, for example, grouping by field. We'd like to automatically fill that field out when assigning an issue to the board.

**Describe the solution you'd like**
It would be nice to be able to set custom fields value, in the same way we can currently set the status value, something like `{custom_field_name}_value: value`.

**Describe alternatives you've considered**
Looked around for another action that would support this, but have not found any.

**Comment by leonsteinhaeuser** [comment]
This workflow automation was not initially intended for the purpose you described. 

Since some things have changed on the GitHub side (e.g. workflow automation on the project level), I think it makes sense to add such a feature.

**Comment by leonsteinhaeuser** [comment]
I had a look at this function and came up with the idea of providing an array of json objects as an argument to update a custom field. The object itself will look like this:

```json
{
    "name":  "text custom field",
    "type":  "text",
    "value":  "custom field text value"
}
```



The supported types are (based on GitHub's custom field types):
- [ ] text: text input (as string)
- [ ] number: number input (integer)
- [ ] date: date input (string) `date --rfc-3339=ns | sed 's/ /T/; s/\(\....\).*\([+-]\)/\1\2/g'` (input as rfc3339 without spaces)
- [ ] single_select: select an option from the select as input value
- [ ] iteration: select a date as option

In the end the workflow for custom fields might look like this:
```yaml
jobs:
  something:
    name: something
    runs-on: ubuntu-latest
    steps:
      - name: some issue task
        uses: leonsteinhaeuser/project-beta-automations@v1.1.0-alpha.1 # is not yet usable
        with:
          gh_token: "pac-token"
          user: "username"
          # organization: sample-org
          project_id: 5
          resource_node_id: ${{ github.event.issue.node_id }}
          # status_value: ${{ env.todo }} # Target status
          custom_fields: '[{"name": "field1", "type": "text", "just a text value"}, {"name": "field2", "type": "text", "just a text value"}]'
```

**Comment by zoebosschaart** [comment]
I would really like that feature as well, as we would like to add a PR or issue straight away to an iteration like this: 
![image](https://user-images.githubusercontent.com/74196884/148369339-1dc5fd41-d83a-4830-b82f-9644296d31ed.png) 

I will follow this thread :)

**Comment by leonsteinhaeuser** [comment]
It would be great if one of you could check the PR I created. In my tests I couldn't find any strange behavior, but it would be great if one of you could check it again. Below is both my organization-based and user-based project automation workflow.

See: https://github.com/leonsteinhaeuser/project-beta-automations/pull/23

------

Organization based test workflow:

```yaml
name: Project automations (organization)

on:
  issues:
    types:
    - opened

env:
  gh_project_token: ${{ secrets.PROJECT_AUTOMATION_TOKEN }}
  project_id: <project-id>
  gh_organization: <organization-name>
  status_todo: "Todo"
  status_in_progress: "In Progress"
  custom_field_values: '[{\"name\": \"Priority\",\"type\": \"text\",\"value\": \"uuid1\"},{\"name\": \"Number\",\"type\": \"number\",\"value\": \"100\"},{\"name\": \"Date\",\"type\": \"date\",\"value\": \"2022-01-28T20:02:27.306+01:00\"},{\"name\": \"Single Select\",\"type\": \"single_select\",\"value\": \"Option 1\"},{\"name\": \"Iteration\",\"type\": \"iteration\",\"value\": \"Iteration 1\"}]'

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - name: 'Move issue to ${{ env.status_todo }}'
        uses: leonsteinhaeuser/project-beta-automations@v1.1.0-alpha.1
        env:
          DEBUG_LOG: "true"
        with:
          gh_token: ${{ env.gh_project_token }}
          organization: ${{ env.gh_organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.status_todo }}

  issue_project_custom_field_update:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    needs:
      - issue_opened_or_reopened
    steps:
      - name: 'Modify custom fields'
        uses: leonsteinhaeuser/project-beta-automations@v1.1.0-alpha.1
        env:
          DEBUG_LOG: "true"
        with:
          gh_token: ${{ env.gh_project_token }}
          organization: ${{ env.gh_organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          operation_mode: custom_field
          custom_field_values: ${{ env.custom_field_values }}
```

User based workflow:

```yaml
name: Project automations (user)

on:
  issues:
    types:
    - opened

env:
  gh_project_token: ${{ secrets.PROJECT_AUTOMATION_TOKEN }}
  project_id: <project-id>
  gh_username: <username>
  status_todo: "Todo"
  status_in_progress: "In Progress"
  custom_field_values: '[{\"name\": \"Priority\",\"type\": \"text\",\"value\": \"uuid1\"},{\"name\": \"Number\",\"type\": \"number\",\"value\": \"100\"},{\"name\": \"Date\",\"type\": \"date\",\"value\": \"2022-01-28T20:02:27.306+01:00\"},{\"name\": \"Single Select\",\"type\": \"single_select\",\"value\": \"Option 1\"},{\"name\": \"Iteration\",\"type\": \"iteration\",\"value\": \"Iteration 1\"}]'

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - name: 'Move issue to ${{ env.status_todo }}'
        uses: leonsteinhaeuser/project-beta-automations@v1.1.0-alpha.1
        env:
          DEBUG_LOG: "true"
        with:
          gh_token: ${{ env.gh_project_token }}
          user: ${{ env.gh_username }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.status_todo }}

  issue_project_custom_field_update:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues'
    needs:
      - issue_opened_or_reopened
    steps:
      - name: 'Modify custom fields'
        uses: leonsteinhaeuser/project-beta-automations@v1.1.0-alpha.1
        env:
          DEBUG_LOG: "true"
        with:
          gh_token: ${{ env.gh_project_token }}
          user: ${{ env.gh_username }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          operation_mode: custom_field
          custom_field_values: ${{ env.custom_field_values }}
```
