### ISSUE TITLE
[BUG] entrypoint.sh: line 9: project.sh: No such file or directory

### ISSUE THREAD

**Issue by leonsteinhaeuser** [leonsteinhaeuser/project-beta-automations#3]
**Describe the bug**
entrypoint.sh is not able to load project.sh

```
/home/runner/work/_actions/leonsteinhaeuser/project-beta-automations/v0.0.2/entrypoint.sh: line 9: project.sh: No such file or directory
```

**To Reproduce**
1. Define the workflow steps with values like
```yaml
    steps:
      - name: 'Move issue to Todo'
        uses: leonsteinhaeuser/project-beta-automations@v0.0.1
        with:
          github_token: $GITHUB_TOKEN
          organization: $ORGANIZATION
          project_id: $PROJECT_NUMBER
          resource_node_id: $ISSUE_ID
          status_value: "Todo"
```

**Expected behavior**
I expected to see the issue on my project board.

**Workflow (please complete the following information):**
 - OS: [e.g. ubuntu-latest]
 - App version [e.g. v0.0.1]
