### ISSUE TITLE
[BUG]: No Cards landing on my project board even though the action completes successfully

### ISSUE THREAD

**Issue by ahuffman** [leonsteinhaeuser/project-beta-automations#30]
**Describe the bug**
Setup actions for new issue and closed issue to move to a "Backlog" and "Done" status column respectively.
Action completes successfully, but no card appears on my board.

I am seeing this in the output of the action logs:

```
Run leonsteinhaeuser/project-beta-automations@v1.1.0
  with:
    gh_token: ***
    organization: MYORG
    project_id: 11
    resource_node_id: I_kwDOGtYcnM5Cfj4V
    status_value: Backlog
    operation_mode: status
  env:
    gh_project_id: 11
    gh_organization: MYORG
    proj_column_backlog: Backlog
    proj_column_done: Done
Run echo "***" | gh auth login --with-token
  echo "***" | gh auth login --with-token
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    gh_project_id: 11
    gh_organization: MYORG
    proj_column_backlog: Backlog
    proj_column_done: Done
Run /home/runner/work/_actions/leonsteinhaeuser/project-beta-automations/v1.1.0/entrypoint.sh "organization" "status" "MYORG" "11" "I_kwDOGtYcnM5Cfj4V" "Backlog"
  /home/runner/work/_actions/leonsteinhaeuser/project-beta-automations/v1.1.0/entrypoint.sh "organization" "status" "MYORG" "11" "I_kwDOGtYcnM5Cfj4V" "Backlog"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    gh_project_id: 11
    gh_organization: MYORG
    proj_column_backlog: Backlog
    proj_column_done: Done
    GITHUB_TOKEN: ***
gh: Resource not accessible by integration
gh: Could not resolve to a node with the global id of 'null'
jq: error (at /tmp/api_response.json:0): Cannot iterate over null (null)
jq: error (at /tmp/api_response.json:0): Cannot iterate over null (null)
gh: Could not resolve to a node with the global id of 'null'
```

**To Reproduce**
1. Using an organization name
2. Using a project board ID.  Can you add some detail into the docs on how to obtain the board ID properly?  I'm assuming I'm using the correct integer, but that could be what's going wrong here.
3.  Using a `${{ secrets.GITHUB_TOKEN }}`

**Expected behavior**
Issue cards appear on the project board in the proper status columns.  I do not get any cards added anywhere to the project.
