### ISSUE TITLE
[Feature Request]: Provide ability to relabel issues based on the project_card moved event or examples if already supported

### ISSUE THREAD

**Issue by ahuffman** [leonsteinhaeuser/project-beta-automations#31]
**Is your feature request related to a problem? Please describe.**

**User Story 1**:
As a Project Manager, I want to manage labels on my issues automatically based upon the column I move an issue to.  This will save everyone time and tedious manual effort.

**User Story 2**:
As a Developer, I have triaged an issue and have now labeled it with a particular status/category of issue.  I would like my project board to reflect the work I did outside of the project board so the project is in-sync with the issue's status and visually represents this to the project team.

**Describe the solution you'd like**
I'm not sure if it's currently supported, but I'd like to see the ability to do 2 things:
1.  Upon moving to another status column, remove a particular label(s), and relabel with an additional label(s) based on status column the card gets moved to.
2. If an issue is labeled outside of the Project, and it gets a particular label(s) move it to a column.

This may already be supported, but I think some examples in the documentation would really help provide some useful project automations.

**Comment by leonsteinhaeuser** [comment]
First of all, thank you for sharing your use cases. Out of the box I would say that this is currently not supported. What I could do is to do some research and check if this can be easily implemented or not. 

I will get back to you when I can show you results.

**Comment by leonsteinhaeuser** [comment]
For your second user story, the following should work:

```yaml
on:
  issues:
    types:
      - labeled

env:
  gh_pat: ${{ secrets.GH_PAT }}
  user: "my-user"
  project_id: 1
  in_progress: "In Progress"
  review_requested: "Review Requested"
  done: Done

jobs:
  issues:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'labeled'
    steps:
      - name: In Progress
        if: github.event.label.name == 'status/in-progress' # label with name: status/in-progress
        uses: leonsteinhaeuser/project-beta-automations@v1.2.0
        with:
          gh_token: ${{ secrets.gh_pat }}
          user: ${{ env.user }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.in_progress }}
      
      - name: Review requested
        if: github.event.label.name == 'status/review-requested' # label with name: status/review-requested
        uses: leonsteinhaeuser/project-beta-automations@v1.2.0
        with:
          gh_token: ${{ secrets.gh_pat }}
          user: ${{ env.user }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.review_requested }}

      - name: Done
        if: github.event.label.name == 'status/done' # label with name: status/done
        uses: leonsteinhaeuser/project-beta-automations@v1.2.0
        with:
          gh_token: ${{ secrets.gh_pat }}
          user: ${{ env.user }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.done }}
```

I haven't verified the behavior, but from my understanding of the GitHub workflow api and my tests for event outputs, this should work.

------

Regarding the first point, unfortunately I don't see a suitable event based on an issue or pull request related to a change in the project view.

See: https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types#event-payload-object-6
