### ISSUE TITLE
Automations start failing

### ISSUE THREAD

**Issue by mustafaozhan** [leonsteinhaeuser/project-beta-automations#34]
**Describe the bug**
Since a couple of days, automations start failing with this error
```
gh: Type mismatch on variable $fieldOption and argument value (ID! / String!)
{errors:[{path:[mutation,updateProjectNextItemField,input,value],extensions:{code:variableMismatch,variableName:fieldOption,typeName:ID!,argumentName:value,errorMessage:Type mismatch},locations:[{line:13,column:17}],message:Type mismatch on variable $fieldOption and argument value (ID! / String!)}]}
```
**To Reproduce**
The step that throws that error:
```yaml
      - name: 'Move PR to "🏗 PR Review"'
        if: github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'review_requested'
        uses: leonsteinhaeuser/project-beta-automations@v1.0.1
        with:
          gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          organization: Oztechan
          project_id: 2
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: "🏗 PR Review"
```

**Expected behavior**
It should continue to update the status of PR, like before it was doing.

**Workflow (please complete the following information):**
 - OS: ubuntu-latest
 - App version: @v1.0.1

**Comment by leonsteinhaeuser** [comment]
@mustafaozhan thank you very much for this information. I can see that you are using an "old" version of this automation. I would suggest you to update the version to "v1.2.0" and check if it works or not. If it still does not work, I would ask you to set the following environment variables and provide the output of this action. 

```yaml
    - name: Move issue to ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@v1.2.0
        env:
          DEBUG_COMMANDS: true
          DEBUG_LOG: true
        with:
          ...
```
