### ISSUE TITLE
[Feature Request] Support for self-hosted runners, where `gh` client might not be present

### ISSUE THREAD

**Issue by calexandre** [leonsteinhaeuser/project-beta-automations#38]
On a `self-hosted` runner environment a lot of common tools are not available, such as the `gh` cli.

One workaround is to ensure an extra action that installs the `gh` before running the `project-beta-automations` action, but it would be nice for the action to test if the `gh` cli is present, and if not, download it from GitHub.

Below is the workaround we implemented in our org to allow the action to run in our self-hosted environment:

```yaml
jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: [self-hosted, ubuntu]
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Install gh
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
      - name: Move issue to Backlog
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_app_secret_key: ${{ secrets.GH_PROJ_AUTOMATION_KEY }}
          gh_app_ID: ${{ secrets.GH_PROJ_AUTOMATION_APP_ID }}
          gh_app_installation_ID: ${{ secrets.GH_PROJ_AUTOMATION_INSTALL_ID }}
          organization: ${{ env.gh_organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Backlog
```
