### ISSUE TITLE
[BUG] : gh: Resource not accessible by integration (App Authentication)

### ISSUE THREAD

**Issue by boojamya** [leonsteinhaeuser/project-beta-automations#40]
Hi, I'm trying to use a GH App to authenticate this workflow. The workflow completes successfully, but doesn't add issue to the project board. After going through the logs, I think I found the problem area:

```log
++ gh api graphql --header 'GraphQL-Features: projects_next_graphql' -f 'query=
    mutation($project:ID!, $resource_id:ID!) {
        addProjectNextItem(input: {projectId: $project, contentId: $resource_id}) {
            projectNextItem {
                id
            }
        }
    }' -f project=xxxxxxx -f resource_id=xxxxxxx --jq .data.addProjectNextItem.projectNextItem.id
gh: Resource not accessible by integration
```

I've double checked my bot permissions and they line up with what you wrote on the readme.

I've also done some debugging and have confirmed that the token is being properly authenticated. 

**Do you have any guidance as to why I'm getting the `gh: Resource not accessible by integration` output?**

Some config info:
```yaml
      - name: Move issue to ${{ env.todo }}
        env:
          DEBUG_COMMANDS: true
          DEBUG_LOG: true
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_app_secret_key: ${{ env.gh_app_secret_key }}
          gh_app_ID: ${{ env.gh_app_ID }}
          gh_app_installation_ID: ${{ env.gh_app_installation_ID }}
```

Much appreciated, thank you.
