### ISSUE TITLE
[BUG] "https://api.github.com/graphql": net/http: invalid header field value "token ***\n" for key Authorization

### ISSUE THREAD

**Issue by zoebosschaart** [leonsteinhaeuser/project-beta-automations#44]
**Describe the bug**
The workflow runs successfully, however in the log output I see the following error:

` Post "https://api.github.com/graphql": net/http: invalid header field value "token ***\n" for key Authorization 
`

I have checked my PAT; it is not expired and has org:write rights. The strange thing is is that it has been working before. Also with update to the newest version of the workflow. 

**To Reproduce**

```
env:
  status_todo: To Refine
  in_progress: Committed
  done: PR's to Review
  new: New
  custom_field_values: '[{\"name\": \"Iteration\",\"type\": \"iteration\",\"value\": \"Sprint 28\"}]'
  gh_organization: RoyalAholdDelhaize
  gh_project_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  job1:
    name: bug_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened') && contains( toJson(github), 'bug' )
    steps:
      - name: 'Move issue to ${{ env.in_progress }}'
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        env:
          DEBUG_LOG: "true"
        with:
          gh_token: ${{ env.gh_project_token }}
          organization: ${{ env.gh_organization }}
          project_id: 46
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.in_progress }}
```

**Expected behavior**
The bug being added to the project board. 

**Workflow (please complete the following information):**
 - OS: ubuntu-20.04
 - App version v1.2.1

**Additional context**
