### ISSUE TITLE
[BUG] entrypoint.sh: local: can only be used in a function

### ISSUE THREAD

**Issue by leonsteinhaeuser** [leonsteinhaeuser/project-beta-automations#5]
**Describe the bug**
entrypoint.sh: local: can only be used in a function

```
entrypoint.sh: local: can only be used in a function
```

**To Reproduce**
1. Define the workflow steps with values like
```yaml
    steps:
      - name: 'Move issue to Todo'
        uses: leonsteinhaeuser/project-beta-automations@v0.0.1
        with:
          github_token: $GITHUB_TOKEN
          organization: $ORGANIZATION
          project_id: $PROJECT_NUMBER
          resource_node_id: $ISSUE_ID
          status_value: "Todo"
```

**Expected behavior**
I expected to see the issue on my project board.

**Workflow (please complete the following information):**
 - OS: [e.g. ubuntu-latest]
 - App version [e.g. v0.0.3]
