### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by FortitudeIT** [leonsteinhaeuser/project-beta-automations#50]
**Describe the bug**
I am trying to move an issue to "In review" on the project board, but it's not moving. My guess is that it's because the PR isn't the same as the issue id?

**To Reproduce**
1. Define the workflow steps with values like
```yaml
name: Project automations
on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
      - closed

# map fields with customized labels
env:
  backlog: Backlog
  in_progress: 🏗 In progress
  testing: Testing
  in_review: In review
  done: Done ✅

jobs:
  pr_opened_or_reopened_or_reviewrequested:
    name: pr_opened_or_reopened_or_reviewrequested
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'review_requested')
    steps:
      - name: Move PR to ${{ env.testing }}
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: xxxx
          organization: abc
          project_id: 3
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.testing }} # Target status
```

**Expected behavior**
The issue is moved to the "In review" lane.

**Comment by leonsteinhaeuser** [comment]
Your guess is correct. The issue ID is not the same as the pull request ID. You can take a look at the workflow file that manages this repository:

https://github.com/leonsteinhaeuser/project-beta-automations/blob/main/.github/workflows/project_automations.yml

**Comment by FortitudeIT** [comment]
So is there any way we could move an issue like this?

**Comment by leonsteinhaeuser** [comment]
I don't know what the pull_request context contains in terms of information, but maybe it is possible to get the linked issue via that context.

**Comment by FortitudeIT** [comment]
They're linked in URLs, but I don't think they're in the response itself, so you'd have to do another API call.

https://docs.github.com/en/rest/pulls/pulls#list-pull-requests

**Comment by leonsteinhaeuser** [comment]
Thanks for investigating the API. This basically allows us to scrape the attached issues from the PR. I'm not sure if this should be covered in this automation, but it could be an interesting feature. If you want, I can suggest a solution that does not require changing the automation.

Otherwise, it will take some time because GitHub has changed the project API, forcing me to basically rewrite some things (v2). After this rewrite is done, I could start implementing this functionality.

**Comment by FortitudeIT** [comment]
Either is good for me :)

**Comment by leonsteinhaeuser** [comment]
@FortitudeIT I invested some time in the past day's, but couldn't fight a reliable solution so far. Going to investigate it further, unless you found a solution.

**Comment by anrico-oltmanns** [comment]
@leonsteinhaeuser no solution found yet? Having the same issue. There has to be a way to move issues and not only pull requests right?

**Comment by leonsteinhaeuser** [comment]
@anrico-oltmanns I have already invested some time to find a solution to this problem. So far I have not had any luck. The problem is that the links I want are not included in the event response I received from the server (ci-workflow). The only solution I have left is to create more API requests and hope that the response will contain the necessary information.

When I have some time, I will take another look and implement this feature.

**Comment by leonsteinhaeuser** [comment]
Status update:

The following two files contain the response that the GitHub server sends when I request the value for a particular pull request.

The first one contains the link to the issue in the **body** field (plain text), the second one does not contain the information at all.

[pr_linked_with_comment.json.log](https://github.com/leonsteinhaeuser/project-beta-automations/files/10124145/pr_linked_with_comment.json.log)
[pr_linked_without_comment.json.log](https://github.com/leonsteinhaeuser/project-beta-automations/files/10124146/pr_linked_without_comment.json.log)

I will investigate this further.

**Comment by leonsteinhaeuser** [comment]
Hello everyone,
I'm sorry it took me so long to respond. In the last few days I had some time to study GitHub's GraphQL API. In doing so, I found out that GitHub supports the "ClosingIssuesReferences" object reference in pull requests.

This functionality would allow me to simply select the linked issues that would be closed by the desired pull request. A list of keywords for closing can be found [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

In the next few days I will create a first version that we can test to see how it works.

**Comment by leonsteinhaeuser** [comment]
Can someone please verify that the new behavior works as you would expect?

You can test this by defining the workflow as follows:

```yaml
  pr_closed:
    name: pr_closed
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    env:
      done: "Done"
    steps:
      - name: Move PR to ${{ env.done }}
        uses: leonsteinhaeuser/project-beta-automations@feat/move-related-issues
        with:
          gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          user: sample-user
          # organization: sample-org
          project_id: 1
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.done }}
          move_related_issues: true
```

Once you specify one of the [GitHub link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) options, the issue should be moved along with the pull request.
