### ISSUE TITLE
[ BUG ]: The single select option Id does not belong to the field

### ISSUE THREAD

**Issue by jaclynjessup** [leonsteinhaeuser/project-beta-automations#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when using the `custom_field_values` variable getting error **The single select option Id does not belong to the field**

### Expected Behavior

Custom field values should be set within the project when triggered

### Version

v2.0.0

### Which github actions runner are you using?

Windows

### Steps To Reproduce

Technically using v2.0.1 but that is not within the drop down at this time.
```
  issue_labeled:
    name: issue_labeled
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'labeled'
    steps:
      - name: Add Issue to Contribution Board
        if: github.event.label.name == 'good first issue' || github.event.label.name == 'help wanted'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        env:
          DEBUG_COMMANDS: true
          DEBUG_LOG: true
        with:
          gh_token: ${{ env.gh_project_token }}
          user: ${{ env.user }}
          project_id: ${{ env.gh_project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          custom_field_values: '[{\"name\": \"Contributions\",\"type\": \"single_select\",\"value\": \"Yes\"}]'
```

Field set up in Project
<img width="1039" alt="project_field" src="https://user-images.githubusercontent.com/23533895/219504110-81de2138-88c5-4288-a46e-dc7387a33ec8.png">

### Relevant log output

```shell
==========================   Debug mode is ON ==========================
PROJECT_UUID: ****
PROJECT_ITEM_UUID: ****
+ response='{data:{updateProjectV2ItemFieldValue:null},errors:[{type:VALIDATION,path:[updateProjectV2ItemFieldValue],locations:[{line:8,column:9}],message:The single select option Id does not belong to the field}]}'
+ log='\n{data:{updateProjectV2ItemFieldValue:null},errors:[{type:VALIDATION,path:[updateProjectV2ItemFieldValue],locations:[{line:8,column:9}],message:The single select option Id does not belong to the field}]}'
+ '[' true == true ']'
+ echo '==========================   Debug mode is ON =========================='
+ echo 'PROJECT_UUID: ****'
+ echo 'PROJECT_ITEM_UUID: ****'
+ echo -e 'log:\n\n{data:{updateProjectV2ItemFieldValue:null},errors:[{type:VALIDATION,path:[updateProjectV2ItemFieldValue],locations:[{line:8,column:9}],message:The single select option Id does not belong to the field}]}'
+ echo '==========================   Debug mode is ON =========================='
log:

{data:{updateProjectV2ItemFieldValue:null},errors:[{type:VALIDATION,path:[updateProjectV2ItemFieldValue],locations:[{line:8,column:9}],message:The single select option Id does not belong to the field}]}
==========================   Debug mode is ON ==========================
```

### Additional context:

This can be seen with several different custom fields 
`custom_field_values: '[{\"name\": \"Type\",\"type\": \"single_select\",\"value\": \"🐛 Bug\"}]'`

`'[{\"name\": \"Priority\",\"type\": \"single_select\",\"value\": \"🌋 Urgent\"}, {\"name\": \"Sprint\",\"type\": \"iteration\",\"value\": \"@current\"}]'`

This error can be seen on multiple projects. I have created a separate repo just to test and still receiving the error.

**Comment by leonsteinhaeuser** [comment]
@jaclynjessup the single_select field is currently not supported. I missed the notification from GitHub that they added this new field. I will try to implement it asap (hopefully this weekend).

**Comment by leonsteinhaeuser** [comment]
The problem is really interesting. If you define icons by their name like `volcano` or by their short code `:volcano`, the identification of the field value fails with the error described above. However, if you define the value selection with the actual icon, the identification works as expected.

Failure:

```yaml
- name: 'Modify custom fields'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.PROJECT_PERMISSIONS_TOKEN }}
          user: leonsteinhaeuser
          project_id: ${{ secrets.PROJECT_ID }}
          resource_node_id: ${{ github.event.issue.node_id }}
          operation_mode: custom_field
          custom_field_values: '[{\"name\": \"Iteration\",\"type\": \"iteration\",\"value\": \"@next\"},{\"name\": \"Reported By Customer\",\"type\": \"single_select\",\"value\": \"Yes\"},{\"name\": \"Priority\",\"type\": \"single_select\",\"value\": \":volcano: High\"}]'
```


Succes:

```yaml
- name: 'Modify custom fields'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.PROJECT_PERMISSIONS_TOKEN }}
          user: leonsteinhaeuser
          project_id: ${{ secrets.PROJECT_ID }}
          resource_node_id: ${{ github.event.issue.node_id }}
          operation_mode: custom_field
          custom_field_values: '[{\"name\": \"Iteration\",\"type\": \"iteration\",\"value\": \"@next\"},{\"name\": \"Reported By Customer\",\"type\": \"single_select\",\"value\": \"Yes\"},{\"name\": \"Priority\",\"type\": \"single_select\",\"value\": \"🌋 High\"}]'
```

![image](https://user-images.githubusercontent.com/42437185/219745288-5f815237-6953-4fd4-9655-087b26a6d4ef.png)

@jaclynjessup please test and confirm that it also works for you if you define the actual icon in the workflow file.
