### ISSUE TITLE
[ FEATURE REQUEST ]: Support for Enterprise Customers

### ISSUE THREAD

**Issue by petrandr** [leonsteinhaeuser/project-beta-automations#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently, this automation plugin lacks support for enterprise customers. This limitation prevents enterprises from leveraging the full potential of the plugin in their workflows. To address this, I would like to request the addition of a new feature that enables support for enterprise customers.

### Describe the solution you'd like:

Introduce an additional input parameter named `gh_host` in the `actions.yml`. This new input would allow users to specify the hostname of their enterprise GitHub instance. By including this parameter, users can authenticate and interact with their enterprise repositories seamlessly.

Additionally, modifying the existing gh login commands within the plugin to include the `gh_host` input would ensure that the authentication process aligns with the user's enterprise environment. This modification would enable seamless integration with enterprise GitHub instances and empower enterprise customers to fully utilize this plugin.

The `gh_host` must be the FQDN of the enterprise installation.

Example
```
name: Project automation on enterprise server
on:
  issues:
    types:
      - opened

env:
  todo: Todo ✏️

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_host: my.github.example.com
          # gh_host: ${{ vars.GITHUB_ENTERPRISE_HOST }} 
          gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          user: sample-user
          # organization: sample-org
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status
```
