### ISSUE TITLE
[BUG] Unable to find the status_value_OPTION_ID, puts things in "No Status"

### ISSUE THREAD

**Issue by roderik** [leonsteinhaeuser/project-beta-automations#9]
**Describe the bug**

**To Reproduce**
1. Define the workflow steps with values like
```yaml
  pr_ready_for_review:
    name: pr_ready_for_review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'ready_for_review'
    steps:
      - name: 'Move PR to "Ready for Review"'
        uses: leonsteinhaeuser/project-beta-automations@v1.0.0
        with:
          gh_token: ${{ secrets.PAT_TOKEN }}
          organization: settlemint
          project_id: 20
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: "Ready for Review"
```

2. log output
```
PROJECT_ID: PN_kwDOATEl-80WyQ
ITEM_ID: PNI_lADOATEl-80Wyc4AAm1J
STATUS_FIELD_ID: MDE2OlByb2plY3ROZXh0RmllbGQ0NTg0Ng==
status_value_OPTION_ID: 
{data:{updateProjectNextItemField:{projectNextItem:{id:PNI_lADOATEl-80Wyc4AAm1J}}}}
```

3. board setup

![CleanShot 2021-10-04 at 10 58 07](https://user-images.githubusercontent.com/16780/135822902-c6dd077c-2141-4513-9fe8-fc0c328ba586.png)

This is modeled after the readme, is there a way to see what options there are for the status_value_OPTION_ID?

**Comment by leonsteinhaeuser** [comment]
The "status_value_OPTION_ID" field cannot be set with the "with" argument. Instead, use the "status_value" field and specify the status option in plain text. The script will automatically get the node_id and assign it to the pr or issue.

In my case, the status option values looked like this:

![project_beta_automation](https://user-images.githubusercontent.com/42437185/135835530-07385aaa-db9f-4db4-a387-15b00c143fd2.png)

You can find this view at:

```
https://github.com/orgs/<your-org>/projects/<project-id>/settings/fields/Status
```

**Comment by roderik** [comment]
That looks the same for me

![CleanShot 2021-10-04 at 12 38 42](https://user-images.githubusercontent.com/16780/135837335-0ba77994-8e6c-4353-8e7b-bba40a7cbf2e.png)

**Comment by roderik** [comment]
Was able to get an error by forking and adding -x and cat's everywhere

the JSON file holds

```
{"data":{"organization":{"projectNext":{"id":"PN_kwDOATEl-80WyQ","fields":{"nodes":[{"id":"MDE2OlByb2plY3ROZXh0RmllbGQ0NTg0NA==","name":"Title","settings":"null"},{"id":"MDE2OlByb2plY3ROZXh0RmllbGQ0NTg0NQ==","name":"Assignees","settings":"null"},{"id":"MDE2OlByb2plY3ROZXh0RmllbGQ0NTg0Ng==","name":"Status","settings":"{\"options\":[{\"id\":\"da36602a\",\"name\":\"Backlog\",\"name_html\":\"Backlog\"},{\"id\":\"f75ad846\",\"name\":\"Selected for Development\",\"name_html\":\"Selected for Development\"},{\"id\":\"47fc9ee4\",\"name\":\"In Progress\",\"name_html\":\"In Progress\"},{\"id\":\"7ceeaea6\",\"name\":\"Ready for Review\",\"name_html\":\"Ready for Review\"},{\"id\":\"98236657\",\"name\":\"Done\",\"name_html\":\"Done\"}]}"},{"id":"MDE2OlByb2plY3ROZXh0RmllbGQ0NTg0Nw==","name":"Labels","settings":"null"},{"id":"MDE2OlByb2plY3ROZXh0RmllbGQ0NTg0OA==","name":"Repository","settings":"null"},{"id":"MDE2OlByb2plY3ROZXh0RmllbGQ0NTg0OQ==","name":"Milestone","settings":"null"}]}}}}}
```

and the command errors with

```
gh: Column value must be a valid value for single_select column
```

**Comment by leonsteinhaeuser** [comment]
I have done some tests and I can see where the problem is. In some cases, if the string is not properly quoted, jq is not able to find the node_id by its value. 

How to reproduce the behavior:

```bash
cat <<EOF > /tmp/api_response.json
{"data":{"organization":{"projectNext":{"id":"PN_kwDOATEl-80WyQ","fields":{"nodes":[{"id":"MDE2OlByb2plY3ROZXh0RmllbGQ0NTg0NA==","name":"Title","settings":"null"},{"id":"MDE2OlByb2plY3ROZXh0RmllbGQ0NTg0NQ==","name":"Assignees","settings":"null"},{"id":"MDE2OlByb2plY3ROZXh0RmllbGQ0NTg0Ng==","name":"Status","settings":"{\"options\":[{\"id\":\"da36602a\",\"name\":\"Backlog\",\"name_html\":\"Backlog\"},{\"id\":\"f75ad846\",\"name\":\"Selected for Development\",\"name_html\":\"Selected for Development\"},{\"id\":\"47fc9ee4\",\"name\":\"In Progress\",\"name_html\":\"In Progress\"},{\"id\":\"7ceeaea6\",\"name\":\"Ready for Review\",\"name_html\":\"Ready for Review\"},{\"id\":\"98236657\",\"name\":\"Done\",\"name_html\":\"Done\"}]}"},{"id":"MDE2OlByb2plY3ROZXh0RmllbGQ0NTg0Nw==","name":"Labels","settings":"null"},{"id":"MDE2OlByb2plY3ROZXh0RmllbGQ0NTg0OA==","name":"Repository","settings":"null"},{"id":"MDE2OlByb2plY3ROZXh0RmllbGQ0NTg0OQ==","name":"Milestone","settings":"null"}]}}}}}
EOF

source gh_api_lib.sh
status_value="Ready for Review"
extractStatusFieldNodeSettingsByValue $status_value
extractStatusFieldNodeSettingsByValue "$status_value" # works just fine
```

**Comment by leonsteinhaeuser** [comment]
I put my changes through some tests and they were successful. As a project board I used the following:
![card_view](https://user-images.githubusercontent.com/42437185/135927168-02a3909f-8eaf-4163-a4e3-a4c5a3b2558f.PNG)
his:

and the associated *GitHub workflow* file:
```yml
name: Project automations backlog project

on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - review_requested
      - closed

jobs:
  issue_opened_and_reopened:
    name: issue_opened_and_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened' || github.event.action == 'reopened'
    steps:
      - name: 'Move issue to Todo'
        uses: leonsteinhaeuser/project-beta-automations@v1.0.1
        with:
          gh_token: ${{ secrets.PROJECT_PERMISSIONS_TOKEN }}
          organization: <my-org>
          project_id: 7
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "Backlog"

  issue_closed:
    name: issue_closed
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: 'Moved issue to Closed'
        uses: leonsteinhaeuser/project-beta-automations@v1.0.1
        with:
          gh_token: ${{ secrets.PROJECT_PERMISSIONS_TOKEN }}
          organization: <my-org>
          project_id: 7
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "Done"

  pr_opened_reopened:
    name: pr_opened_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'reopened'
    steps:
      - name: 'Move PR to "In Progress"'
        uses: leonsteinhaeuser/project-beta-automations@v1.0.1
        with:
          gh_token: ${{ secrets.PROJECT_PERMISSIONS_TOKEN }}
          organization: <my-org>
          project_id: 7
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: "In Progress"

  pr_ready_for_review_review_requested:
    name: pr_ready_for_review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'ready_for_review' || github.event.action == 'review_requested'
    steps:
      - name: 'Move PR to "Ready for Review"'
        uses: leonsteinhaeuser/project-beta-automations@v1.0.1
        with:
          gh_token: ${{ secrets.PROJECT_PERMISSIONS_TOKEN }}
          organization: <my-org>
          project_id: 7
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: "Ready for Review"

  pr_closed:
    name: pr_closed
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: 'Move PR to "Closed"'
        uses: leonsteinhaeuser/project-beta-automations@v1.0.1
        with:
          gh_token: ${{ secrets.PROJECT_PERMISSIONS_TOKEN }}
          organization: <my-org>
          project_id: 7
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: "Done"
```

------

If it works for you as well, I will close the ticket.
